<<<<<<< HEAD
name: Terraform Proxmox
=======
name: Terraform Test
>>>>>>> adbae27 (add workflow)

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
=======
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
>>>>>>> adbae27 (add workflow)
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve
